version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crosscourt-taxonomy
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
